### ISSUE TITLE
RuntimeError: Task ... got Future ... attached to a different loop

### ISSUE THREAD

**Issue by mill1000** [mill1000/midea-msmart#74]
Originally from https://github.com/mac-zhou/midea-ac-py/issues/221#issuecomment-1722081202

```
root@debian:/home/jacek# msmart-ng discover
INFO:msmart.cli:Discovering all devices on local network.
INFO:msmart.cloud:Using Midea cloud server: https://mp-prod.appsmb.com (China: False).
Traceback (most recent call last):
  File "/usr/local/bin/msmart-ng", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/msmart/cli.py", line 188, in main
    _run(parser.parse_args())
  File "/usr/local/lib/python3.9/dist-packages/msmart/cli.py", line 119, in _run
    asyncio.run(args.func(args))
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/dist-packages/msmart/cli.py", line 21, in _discover
    devices = await Discover.discover(account=args.account, password=args.password, discovery_packets=args.count)
  File "/usr/local/lib/python3.9/dist-packages/msmart/discover.py", line 188, in discover
    devices = await asyncio.gather(*protocol.tasks)
  File "/usr/local/lib/python3.9/dist-packages/msmart/discover.py", line 401, in _get_device
    await Discover.connect(dev)
  File "/usr/local/lib/python3.9/dist-packages/msmart/discover.py", line 409, in connect
    success = await Discover._authenticate_device(dev)
  File "/usr/local/lib/python3.9/dist-packages/msmart/discover.py", line 359, in _authenticate_device
    cloud = await Discover._get_cloud()
  File "/usr/local/lib/python3.9/dist-packages/msmart/discover.py", line 225, in _get_cloud
    async with cls._lock:
  File "/usr/lib/python3.9/asyncio/locks.py", line 14, in __aenter__
    await self.acquire()
  File "/usr/lib/python3.9/asyncio/locks.py", line 120, in acquire
    await fut
RuntimeError: Task <Task pending name='Task-3' coro=<Discover._get_device() running at /usr/local/lib/python3.9/dist-packages/msmart/discover.py:401>> got Future <Future pending> attached to a different loop
root@debian:/home/jacek#
```

Could be related the same issue discussed here: https://stackoverflow.com/questions/55918048/asyncio-semaphore-runtimeerror-task-got-future-attached-to-a-different-loop

**Comment by mill1000** [comment]
So fair I've been unable to reproduce this. Unit tests run on Python 3.9 to 3.11.

**Comment by YoMan12** [comment]
Python 3.9.2, msmart 2023.9.4

**Comment by mill1000** [comment]
Thanks. Very odd. I haven't been able to recreate it yet.

Are you running on an esoteric system? e.g. anything besides x86_64 or ARM, a RT kernel, or an alternate Python interpreter?

**Comment by YoMan12** [comment]
to be honest I'm a very beginner of linux systems so I'm not always sure what am I doing, if am I doing properly, etc....

I'm instaling it on a x86 (very old DELL laptop)
In the meantime I tried to reinstall and i f..ed up something :(
Would You like to give a hand ??
```
jacek@debian:~$ pip3 uninstall msmart
Found existing installation: msmart 0.2.5
Uninstalling msmart-0.2.5:
  Would remove:
    /home/jacek/.local/lib/python3.9/site-packages/msmart-0.2.5.dist-info/*
    /home/jacek/.local/lib/python3.9/site-packages/msmart/*
Proceed (y/n)? y
  Successfully uninstalled msmart-0.2.5
jacek@debian:~$ pip3 install msmart
Requirement already satisfied: msmart in /usr/local/lib/python3.9/dist-packages (0.2.5)
Requirement already satisfied: click in ./.local/lib/python3.9/site-packages (from msmart) (8.1.7)
Requirement already satisfied: pycryptodome in ./.local/lib/python3.9/site-packages (from msmart) (3.18.0)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from msmart) (2.25.1)
Requirement already satisfied: ifaddr in ./.local/lib/python3.9/site-packages (from msmart) (0.2.0)
jacek@debian:~$ msmart-ng --discover
Traceback (most recent call last):
  File "/usr/local/bin/msmart-ng", line 5, in <module>
    from msmart.cli import main
ImportError: cannot import name 'main' from 'msmart.cli' (/usr/local/lib/python3.9/dist-packages/msmart/cli.py)
jacek@debian:~$

```

**Comment by mill1000** [comment]
No problem.

1. Uninstall the legacy msmart
`pip uninstall msmart`

2. Install my new version
`pip install msmart-ng`

**Comment by YoMan12** [comment]
Seems like it does not want to be uninstalled:
```
jacek@debian:~$ sudo pip uninstall msmart
[sudo] hasło użytkownika jacek:
Found existing installation: msmart 0.2.5
Uninstalling msmart-0.2.5:
  Would remove:
    /usr/local/bin/midea-discover
    /usr/local/lib/python3.9/dist-packages/msmart-0.2.5.dist-info/*
    /usr/local/lib/python3.9/dist-packages/msmart/*
  Would not remove (might be manually added):
    /usr/local/lib/python3.9/dist-packages/msmart/base_device.py
    /usr/local/lib/python3.9/dist-packages/msmart/device/AC/device.py
    /usr/local/lib/python3.9/dist-packages/msmart/device/AC/test_command.py
    /usr/local/lib/python3.9/dist-packages/msmart/device/AC/test_device.py
    /usr/local/lib/python3.9/dist-packages/msmart/discover.py
    /usr/local/lib/python3.9/dist-packages/msmart/tests/__init__.py
    /usr/local/lib/python3.9/dist-packages/msmart/tests/test_cloud.py
    /usr/local/lib/python3.9/dist-packages/msmart/tests/test_discover.py
    /usr/local/lib/python3.9/dist-packages/msmart/tests/test_lan.py
Proceed (y/n)? y
  Successfully uninstalled msmart-0.2.5
jacek@debian:~$ sudo pip install msmart-ng
Requirement already satisfied: msmart-ng in /usr/local/lib/python3.9/dist-packages (2023.9.4)
Requirement already satisfied: pycryptodome in /usr/local/lib/python3.9/dist-packages (from msmart-ng) (3.18.0)
Requirement already satisfied: httpx in /usr/local/lib/python3.9/dist-packages (from msmart-ng) (0.25.0)
Requirement already satisfied: sniffio in /usr/local/lib/python3.9/dist-packages (from httpx->msmart-ng) (1.3.0)
Requirement already satisfied: idna in /usr/lib/python3/dist-packages (from httpx->msmart-ng) (2.10)
Requirement already satisfied: certifi in /usr/lib/python3/dist-packages (from httpx->msmart-ng) (2020.6.20)
Requirement already satisfied: httpcore<0.19.0,>=0.18.0 in /usr/local/lib/python3.9/dist-packages (from httpx->msmart-ng) (0.18.0)
Requirement already satisfied: h11<0.15,>=0.13 in /usr/local/lib/python3.9/dist-packages (from httpcore<0.19.0,>=0.18.0->httpx->msmart-ng) (0.14.0)
Requirement already satisfied: anyio<5.0,>=3.0 in /usr/local/lib/python3.9/dist-packages (from httpcore<0.19.0,>=0.18.0->httpx->msmart-ng) (4.0.0)
Requirement already satisfied: exceptiongroup>=1.0.2 in /usr/local/lib/python3.9/dist-packages (from anyio<5.0,>=3.0->httpcore<0.19.0,>=0.18.0->httpx->msmart-ng) (1.1.3)
jacek@debian:~$

```

**Comment by mill1000** [comment]
Ok, maybe try uninstalling both packages and then reinstall msmart-ng

**Comment by YoMan12** [comment]
OK. I'm back .... to previous issue :)
```
Installing collected packages: msmart-ng
Successfully installed msmart-ng-2023.9.5
jacek@debian:~$ msmart-ng -discover
usage: msmart-ng [-h] [-v] {discover,query,download} ...
msmart-ng: error: the following arguments are required: command
jacek@debian:~$ msmart-ng discover
INFO:msmart.cli:Discovering all devices on local network.
WARNING:msmart.discover:Reported device IP 192.168.8.145 does not match received IP 192.168.8.151.
INFO:msmart.cloud:Using Midea cloud server: https://mp-prod.appsmb.com (China: False).
WARNING:msmart.discover:Reported device IP 192.168.8.126 does not match received IP 192.168.8.154.
WARNING:msmart.discover:Reported device IP 192.168.8.128 does not match received IP 192.168.8.152.
Traceback (most recent call last):
  File "/usr/local/bin/msmart-ng", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/msmart/cli.py", line 232, in main
    _run(parser.parse_args())
  File "/usr/local/lib/python3.9/dist-packages/msmart/cli.py", line 155, in _run
    asyncio.run(args.func(args))
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/dist-packages/msmart/cli.py", line 21, in _discover
    devices = await Discover.discover(account=args.account, password=args.password, discovery_packets=args.count)
  File "/usr/local/lib/python3.9/dist-packages/msmart/discover.py", line 188, in discover
    devices = await asyncio.gather(*protocol.tasks)
  File "/usr/local/lib/python3.9/dist-packages/msmart/discover.py", line 401, in _get_device
    await Discover.connect(dev)
  File "/usr/local/lib/python3.9/dist-packages/msmart/discover.py", line 409, in connect
    success = await Discover._authenticate_device(dev)
  File "/usr/local/lib/python3.9/dist-packages/msmart/discover.py", line 359, in _authenticate_device
    cloud = await Discover._get_cloud()
  File "/usr/local/lib/python3.9/dist-packages/msmart/discover.py", line 225, in _get_cloud
    async with cls._lock:
  File "/usr/lib/python3.9/asyncio/locks.py", line 14, in __aenter__
    await self.acquire()
  File "/usr/lib/python3.9/asyncio/locks.py", line 120, in acquire
    await fut
RuntimeError: Task <Task pending name='Task-3' coro=<Discover._get_device() running at /usr/local/lib/python3.9/dist-packages/msmart/discover.py:401>> got Future <Future pending> attached to a different loop
jacek@debian:~$

```

**Comment by mill1000** [comment]
Ok, when I'm back in town in a few days I'll try your specific Python version.

**Comment by YoMan12** [comment]
if it is neccesry I can try a different one :)

**Comment by mill1000** [comment]
Well I'm still unable to recreate your issue, and I can't explain why, but I think I have a fix anyway in #82.

You can test this fix via pip
```
pip install git+https://github.com/mill1000/midea-msmart@issue/runtime_error_with_lock
```

**Comment by YoMan12** [comment]
> Well I'm still unable to recreate your issue, and I can't explain why, but I think I have a fix anyway in #82.
> 
> You can test this fix via pip
> 
> ```
> pip install git+https://github.com/mill1000/midea-msmart@issue/runtime_error_with_lock
> ```

OK. I will try on this weekend when I will be local :)

**Comment by YoMan12** [comment]
HI, I've got some break due to lack of time for anything.
But now I've tried Your proposition and it seems to be not actual :(
```
jacek@debian:~$ pip install git+https://github.com/mill1000/midea-msmart@issue/runtime_error_with_lock
Collecting git+https://github.com/mill1000/midea-msmart@issue/runtime_error_with_lock
  Cloning https://github.com/mill1000/midea-msmart (to revision issue/runtime_error_with_lock) to /tmp/pip-req-build-1634uw2_
  Running command git clone -q https://github.com/mill1000/midea-msmart /tmp/pip-req-build-1634uw2_
  WARNING: Did not find branch or tag 'issue/runtime_error_with_lock', assuming revision or ref.
  Running command git checkout -q issue/runtime_error_with_lock
  error: ścieżka „issue/runtime_error_with_lock” nie pasuje do żadnych plików znanych gitowi
WARNING: Discarding git+https://github.com/mill1000/midea-msmart@issue/runtime_error_with_lock. Command errored out with exit status 1: git checkout -q issue/runtime_error_with_lock Check the logs for full command output.
ERROR: Command errored out with exit status 1: git checkout -q issue/runtime_error_with_lock Check the logs for full command output.
```
It is written that "the path do not fit to any files known of Git".  Have You deleted it?

**Comment by mill1000** [comment]
Hey there. I went ahead and merged this fix into main some time ago.

You can just install the latest release.
```
pip install msmart-ng==2023.11.0
```

**Comment by YoMan12** [comment]
Ha! .. ! Yeah ... now it works, devices dicovered :) Thanx for Ur help ;)
